# -*- coding: utf-8 -*-
"""FaceBookNarcissm_R.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15biIshHdz5ggDXhjMFW1IgMSA030L8nh
"""

facebookData <- read.delim("/content/FacebookNarcissism.dat", header = TRUE)

graph <- ggplot(facebookData, aes(x,y))

graph <- ggplot(facebookData, aes(NPQC_R_Total, Rating))

graph + geom_point()

graph + geom_point(shape = 17)

graph + geom_point(size = 6)

graph + geom_point(aes(colour = Rating_Type))

graph + geom_point(aes(colour = Rating_Type), position = "jitter")

graph + geom_point(aes(shape = Rating_Type), position = "jitter")

